# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cast_id', models.IntegerField()),
                ('cast_name', models.CharField(max_length=255)),
                ('movie_id', models.IntegerField()),
                ('show_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_id', models.IntegerField()),
                ('director_name', models.CharField(max_length=255)),
                ('movie_id', models.IntegerField()),
                ('show_id', models.IntegerField()),
                ('director_desc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_id', models.CharField(max_length=255)),
                ('genre_name', models.CharField(max_length=255)),
                ('movie_id', models.IntegerField()),
                ('show_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('movie_name', models.CharField(max_length=255)),
                ('director_id', models.IntegerField()),
                ('release_date', models.IntegerField()),
                ('producer_id', models.IntegerField()),
                ('time_movie', models.IntegerField()),
                ('cast_id', models.IntegerField()),
                ('ratings_id', models.IntegerField()),
                ('genre_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.IntegerField()),
                ('plan_id', models.IntegerField()),
                ('payment_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.IntegerField()),
                ('plan_name', models.CharField(max_length=255)),
                ('plan_desc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer_id', models.IntegerField()),
                ('producer_name', models.CharField(max_length=255)),
                ('movie_id', models.IntegerField()),
                ('show_id', models.IntegerField()),
                ('producer_desc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings_id', models.IntegerField()),
                ('show_id', models.IntegerField()),
                ('movie_id', models.IntegerField()),
                ('ratings', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_id', models.IntegerField()),
                ('show_name', models.CharField(max_length=255)),
                ('director_id', models.IntegerField()),
                ('release_date', models.IntegerField()),
                ('seasons', models.IntegerField()),
                ('cast_id', models.IntegerField()),
                ('ratings_id', models.IntegerField()),
                ('genre_id', models.IntegerField()),
                ('producer_id', models.IntegerField()),
                ('time_episode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_fname', models.CharField(max_length=255)),
                ('user_lname', models.CharField(max_length=255)),
                ('user_email', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('user_payment_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('plan_id', models.IntegerField()),
                ('user_plan_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Watched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('show_id', models.IntegerField()),
                ('movie_id', models.IntegerField()),
                ('ratings_id', models.IntegerField()),
            ],
        ),
    ]
