# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('director_id', models.IntegerField()),
                ('release_date', models.IntegerField()),
                ('cast_id', models.IntegerField()),
                ('ratings_id', models.IntegerField()),
                ('genre_id', models.IntegerField()),
                ('producer_id', models.IntegerField()),
                ('time', models.IntegerField()),
                ('show_id', models.IntegerField()),
                ('movie_id', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='cast',
            name='movie_id',
        ),
        migrations.RemoveField(
            model_name='cast',
            name='show_id',
        ),
        migrations.RemoveField(
            model_name='director',
            name='movie_id',
        ),
        migrations.RemoveField(
            model_name='director',
            name='show_id',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='movie_id',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='show_id',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='cast_id',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='director_id',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre_id',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_name',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='producer_id',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='ratings_id',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='time_movie',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='movie_id',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='show_id',
        ),
        migrations.RemoveField(
            model_name='ratings',
            name='movie_id',
        ),
        migrations.RemoveField(
            model_name='ratings',
            name='show_id',
        ),
        migrations.RemoveField(
            model_name='show',
            name='cast_id',
        ),
        migrations.RemoveField(
            model_name='show',
            name='director_id',
        ),
        migrations.RemoveField(
            model_name='show',
            name='genre_id',
        ),
        migrations.RemoveField(
            model_name='show',
            name='producer_id',
        ),
        migrations.RemoveField(
            model_name='show',
            name='ratings_id',
        ),
        migrations.RemoveField(
            model_name='show',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='show',
            name='show_name',
        ),
        migrations.RemoveField(
            model_name='show',
            name='time_episode',
        ),
        migrations.RemoveField(
            model_name='watched',
            name='movie_id',
        ),
        migrations.RemoveField(
            model_name='watched',
            name='show_id',
        ),
    ]
