# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 03:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0002_auto_20171010_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='access',
            name='id',
        ),
        migrations.RemoveField(
            model_name='cast',
            name='id',
        ),
        migrations.RemoveField(
            model_name='content',
            name='id',
        ),
        migrations.RemoveField(
            model_name='director',
            name='id',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='id',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='id',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='ratings',
            name='id',
        ),
        migrations.RemoveField(
            model_name='show',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.RemoveField(
            model_name='userpayment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='userplan',
            name='id',
        ),
        migrations.RemoveField(
            model_name='watched',
            name='id',
        ),
        migrations.AlterField(
            model_name='access',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflix.User'),
        ),
        migrations.AlterField(
            model_name='access',
            name='username',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cast',
            name='cast_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='content',
            name='cast_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflix.Cast'),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='content',
            name='director_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflix.Director'),
        ),
        migrations.AlterField(
            model_name='content',
            name='genre_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflix.Genre'),
        ),
        migrations.AlterField(
            model_name='content',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflix.Movie'),
        ),
        migrations.AlterField(
            model_name='content',
            name='producer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflix.Producer'),
        ),
        migrations.AlterField(
            model_name='content',
            name='ratings_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflix.Ratings'),
        ),
        migrations.AlterField(
            model_name='content',
            name='show_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflix.Show'),
        ),
        migrations.AlterField(
            model_name='director',
            name='director_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='plan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflix.Plan'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producer',
            name='producer_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='ratings_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='show',
            name='show_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='payment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflix.Payment'),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflix.User'),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='user_payment_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='plan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflix.Plan'),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflix.User'),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='user_plan_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='watched',
            name='ratings_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflix.Ratings'),
        ),
        migrations.AlterField(
            model_name='watched',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflix.User'),
        ),
        migrations.AlterField(
            model_name='watched',
            name='watched_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
